import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Button from '@mui/material/Button';
import dynamic from "next/dynamic";
// import { Time } from '../component/time';
const Time = dynamic(() => import("../component/time").then((module) => module.Time), { ssr: false });

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [data, setData] = useState(null);

  useEffect(() => {
    console.log(process.env.NEXT_PUBLIC_ATTENDANCE_URL);
    fetch(process.env.NEXT_PUBLIC_ATTENDANCE_URL ?? '')
      .then((response) => response.json())
      .then((data) => setData(data));
  }, []);

  console.log({ data });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Time></Time>
      </div>
      <div>
        <Button variant="contained">出勤</Button>
        <Button variant="contained">退勤</Button>
      </div>
      <div>
        <Button variant="contained">タイムカード</Button>
        <Button variant="contained">出勤状況</Button>
        <Button variant="contained">ヘルプ</Button>
      </div>
    </>
  );
}
